spring:
  datasource:
    url: jdbc:mysql://localhost:3306/EmployeeManagement
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

  output:
    ansi:
      enabled: always